server:
  port: 8081

spring:
  application:
    name: service-hi
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.146:3306/1802a?useUnicode=true&characterEncoding=utf-8
    #url: jdbc:mysql://192.168.31.10:3306/ccc?useUnicode=true&characterEncoding=utf-8
    username: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jk.model






