eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  rabbitmq:
    host: 127.0.0.1
    password: sunlj
    port: 5672
    publisher-confirms: true
    username: sunlj
    virtual-host: /vhost